"""empty message

Revision ID: 1b8fe8184178
Revises: 2ed14a3ff9f4
Create Date: 2016-07-18 18:14:23.442114

"""

# revision identifiers, used by Alembic.
revision = '1b8fe8184178'
down_revision = '2ed14a3ff9f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('giv_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'giv_id')
    ### end Alembic commands ###
