"""empty message

Revision ID: 2ed14a3ff9f4
Revises: b230172d8c08
Create Date: 2016-07-15 16:41:16.777082

"""

# revision identifiers, used by Alembic.
revision = '2ed14a3ff9f4'
down_revision = 'b230172d8c08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('own', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'own')
    ### end Alembic commands ###
