"""empty message

Revision ID: 4e7e72d20ab7
Revises: 1b033923dc71
Create Date: 2016-11-17 13:05:57.995457

"""

# revision identifiers, used by Alembic.
revision = '4e7e72d20ab7'
down_revision = '1b033923dc71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'games', ['id'])
    op.create_unique_constraint(None, 'ratings', ['id'])
    op.add_column('users', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('lng', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'lng')
    op.drop_column('users', 'lat')
    op.drop_constraint(None, 'ratings', type_='unique')
    op.drop_constraint(None, 'games', type_='unique')
    ### end Alembic commands ###
