"""empty message

Revision ID: 87e5adb11979
Revises: 1b8fe8184178
Create Date: 2016-07-18 19:16:42.498154

"""

# revision identifiers, used by Alembic.
revision = '87e5adb11979'
down_revision = '1b8fe8184178'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['ratings.rec_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ratings')
    ### end Alembic commands ###
