"""empty message

Revision ID: b230172d8c08
Revises: fb5dba328ce9
Create Date: 2016-07-15 16:19:56.139184

"""

# revision identifiers, used by Alembic.
revision = 'b230172d8c08'
down_revision = 'fb5dba328ce9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('games_game_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_game_id_fkey', 'games', 'users', ['game_id'], ['id'])
    op.drop_column('games', 'user_id')
    op.drop_table('user_games')
    ### end Alembic commands ###
