"""empty message

Revision ID: fb5dba328ce9
Revises: bb0961aa322e
Create Date: 2016-07-12 18:29:40.424850

"""

# revision identifiers, used by Alembic.
revision = 'fb5dba328ce9'
down_revision = 'bb0961aa322e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'games', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'games', type_='unique')
    ### end Alembic commands ###
